apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: o84upjkuq-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/o84upjkuq-java-quarkus-gitops